name: deployment

on:
  push:
    branches: [ "main" ] 

needs: "Build site"

jobs:

  deploy:

    runs-on: ubuntu-20.04

    steps:
    - name: deploy 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASS }}
        script: |
          cd ~/website/frontend/deployment
          bash deploy.sh